Feature/get member by email
td-org-uit-no/tdctl-api pull request #36
Opened 2022-10-29 11:19 UTC by FredrikMorstad

# :sparkles: GET `api/member/email/{email}`
 - :information_source: Endpoint for getting user by their email
 - :lock: admin protected 
 ## Minor updates
 - ### :lock: Update response to 403 for admin updating admins
 - ### :mailbox_with_no_mail: update response for `api/event/{id}/join`
   - Returns {'max': True/False} based on the event being full

2022-11-11 11:48 UTC, VetleWoie requested changes
Looks good to me, aside from some rouge commented-out code.

2022-11-11 12:03 UTC, seblj commented on tests/test_endpoints/test_members.py
> +    print(response.json())
Probably don't need to print in the tests as it clutters the output

2022-11-11 12:03 UTC, seblj commented on tests/test_endpoints/test_members.py
> +    print(response.json())
Here as well

2022-11-18 09:53 UTC, VetleWoie approved these changes

2022-11-18 09:53 UTC, merged